/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class MathUiModule extends AbstractMathUiModule {
}
