/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathScopeProvider extends DelegatingScopeProvider {
}
