/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd

import dk.sdu.mmmi.mdsd.math.MathStandaloneSetupGenerated

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MathStandaloneSetup extends MathStandaloneSetupGenerated {

	def static void doSetup() {
		new MathStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
