/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd

import dk.sdu.mmmi.mdsd.math.AbstractMathRuntimeModule

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MathRuntimeModule extends AbstractMathRuntimeModule {
}
