/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MathUiModule extends AbstractMathUiModule {
  public MathUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
