/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide

import com.google.inject.Guice
import dk.sdu.mmmi.mdsd.MathRuntimeModule
import dk.sdu.mmmi.mdsd.MathStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MathIdeSetup extends MathStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MathRuntimeModule, new MathIdeModule))
	}
	
}
