/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.math.ui.internal.MathActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathActivator.getInstance().getInjector("dk.sdu.mmmi.mdsd.math.Math");
	}

}
