/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MathAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dk/sdu/mmmi/mdsd/math/parser/antlr/internal/InternalMath.tokens");
	}
}
