/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.math.generator;

import com.google.common.collect.Iterators;
import dk.sdu.mmmi.mdsd.math.math.Binding;
import dk.sdu.mmmi.mdsd.math.math.Div;
import dk.sdu.mmmi.mdsd.math.math.Expression;
import dk.sdu.mmmi.mdsd.math.math.Ext;
import dk.sdu.mmmi.mdsd.math.math.ExternalP;
import dk.sdu.mmmi.mdsd.math.math.LetBinding;
import dk.sdu.mmmi.mdsd.math.math.MathExp;
import dk.sdu.mmmi.mdsd.math.math.MathNumber;
import dk.sdu.mmmi.mdsd.math.math.Minus;
import dk.sdu.mmmi.mdsd.math.math.Mult;
import dk.sdu.mmmi.mdsd.math.math.Par;
import dk.sdu.mmmi.mdsd.math.math.Plus;
import dk.sdu.mmmi.mdsd.math.math.VarBinding;
import dk.sdu.mmmi.mdsd.math.math.VariableUse;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MathGenerator extends AbstractGenerator {
  private static Map<String, String> variables;
  
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    final MathExp math = Iterators.<MathExp>filter(resource.getAllContents(), MathExp.class).next();
    this.generateMathFile(math, "math_expression", fsa);
  }
  
  public void generateMathFile(final MathExp math, final String pkgName, final IFileSystemAccess2 fsa2) {
    String _name = math.getName();
    String _plus = ((pkgName + "/") + _name);
    String _plus_1 = (_plus + ".java");
    fsa2.generateFile(_plus_1, this.GenJF(math));
  }
  
  public String GenJF(final MathExp exp) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("package math_expression;");
    _builder.newLine();
    _builder.append("public class ");
    String _name = exp.getName();
    _builder.append(_name);
    _builder.append(" {");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    String _genVars = this.genVars(exp);
    _builder.append(_genVars, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    String _genCompute = this.genCompute(exp);
    _builder.append(_genCompute, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("\t");
    String _genExternal = this.genExternal(exp);
    _builder.append(_genExternal, "\t");
    _builder.newLineIfNotEmpty();
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public String genVars(final MathExp exp) {
    StringConcatenation _builder = new StringConcatenation();
    {
      EList<VarBinding> _variables = exp.getVariables();
      for(final VarBinding v : _variables) {
        _builder.append("public int ");
        String _name = v.getName();
        _builder.append(_name);
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    return _builder.toString();
  }
  
  public String genCompute(final MathExp exp) {
    MathGenerator.compute(exp);
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("public void compute() {");
    _builder.newLine();
    {
      EList<VarBinding> _variables = exp.getVariables();
      for(final VarBinding v : _variables) {
        _builder.append("\t");
        String _name = v.getName();
        _builder.append(_name, "\t");
        _builder.append(" = ");
        String _computeExpression = MathGenerator.computeExpression(v);
        _builder.append(_computeExpression, "\t");
        _builder.append(";");
        _builder.newLineIfNotEmpty();
      }
    }
    _builder.append("}");
    _builder.newLine();
    return _builder.toString();
  }
  
  public String genExternal(final MathExp exp) {
    StringConcatenation _builder = new StringConcatenation();
    {
      int _size = exp.getExternals().size();
      boolean _greaterThan = (_size > 0);
      if (_greaterThan) {
        _builder.append("private External external;");
        _builder.newLine();
        _builder.append("  ");
        _builder.newLine();
        _builder.append("public ");
        String _name = exp.getName();
        _builder.append(_name);
        _builder.append("(External external) {");
        _builder.newLineIfNotEmpty();
        _builder.append("\t");
        _builder.append("this.external = external;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.append("interface External {");
        _builder.newLine();
        {
          EList<Ext> _externals = exp.getExternals();
          for(final Ext func : _externals) {
            _builder.append("\t");
            _builder.append("int ");
            String _name_1 = func.getName();
            _builder.append(_name_1, "\t");
            _builder.append("(");
            String _genExt = this.genExt(func);
            _builder.append(_genExt, "\t");
            _builder.append(");");
            _builder.newLineIfNotEmpty();
          }
        }
        _builder.append("}");
        _builder.newLine();
      }
    }
    return _builder.toString();
  }
  
  public String genExt(final Ext ext) {
    int _size = ext.getParameters().size();
    switch (_size) {
      case 1:
        return "int a";
      case 2:
        return "int a, int b";
      default:
        return "";
    }
  }
  
  public static Map<String, String> compute(final MathExp math) {
    Map<String, String> _xblockexpression = null;
    {
      HashMap<String, String> _hashMap = new HashMap<String, String>();
      MathGenerator.variables = _hashMap;
      EList<VarBinding> _variables = math.getVariables();
      for (final VarBinding varBinding : _variables) {
        MathGenerator.computeExpression(varBinding);
      }
      _xblockexpression = MathGenerator.variables;
    }
    return _xblockexpression;
  }
  
  protected static String _computeExpression(final VarBinding binding) {
    MathGenerator.variables.put(binding.getName(), MathGenerator.computeExpression(binding.getExpression()));
    return MathGenerator.variables.get(binding.getName());
  }
  
  protected static String _computeExpression(final MathNumber exp) {
    return Integer.valueOf(exp.getValue()).toString();
  }
  
  protected static String _computeExpression(final Plus exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    String _plus = (_computeExpression + " + ");
    String _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_plus + _computeExpression_1);
  }
  
  protected static String _computeExpression(final Minus exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    String _plus = (_computeExpression + " - ");
    String _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_plus + _computeExpression_1);
  }
  
  protected static String _computeExpression(final Mult exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    String _plus = (_computeExpression + " * ");
    String _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_plus + _computeExpression_1);
  }
  
  protected static String _computeExpression(final Div exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getLeft());
    String _plus = (_computeExpression + " / ");
    String _computeExpression_1 = MathGenerator.computeExpression(exp.getRight());
    return (_plus + _computeExpression_1);
  }
  
  protected static String _computeExpression(final LetBinding exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getBody());
    String _plus = ("(" + _computeExpression);
    return (_plus + ")");
  }
  
  protected static String _computeExpression(final VariableUse exp) {
    String _computeBinding = MathGenerator.computeBinding(exp.getRef());
    String _plus = ("(" + _computeBinding);
    return (_plus + ")");
  }
  
  protected static String _computeExpression(final Par exp) {
    String _computeExpression = MathGenerator.computeExpression(exp.getExp());
    String _plus = ("(" + _computeExpression);
    return (_plus + " )");
  }
  
  protected static String _computeBinding(final VarBinding binding) {
    String _xblockexpression = null;
    {
      boolean _containsKey = MathGenerator.variables.containsKey(binding.getName());
      boolean _not = (!_containsKey);
      if (_not) {
        MathGenerator.computeExpression(binding);
      }
      _xblockexpression = MathGenerator.variables.get(binding.getName());
    }
    return _xblockexpression;
  }
  
  protected static String _computeBinding(final LetBinding binding) {
    String _computeExpression = MathGenerator.computeExpression(binding.getBinding());
    String _plus = ("(" + _computeExpression);
    return (_plus + ")");
  }
  
  protected static String _computeExpression(final ExternalP exp) {
    int _size = exp.getArgs().size();
    boolean _greaterThan = (_size > 0);
    if (_greaterThan) {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("this.external.");
      String _name = exp.getRef().getName();
      _builder.append(_name);
      _builder.append("(");
      {
        EList<Expression> _args = exp.getArgs();
        boolean _hasElements = false;
        for(final Expression x : _args) {
          if (!_hasElements) {
            _hasElements = true;
          } else {
            _builder.appendImmediate(", ", "");
          }
          String _computeExpression = MathGenerator.computeExpression(x);
          _builder.append(_computeExpression);
        }
      }
      _builder.append(")");
      _builder.newLineIfNotEmpty();
      return _builder.toString();
    } else {
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("this.external.");
      String _name_1 = exp.getRef().getName();
      _builder_1.append(_name_1);
      _builder_1.append("()");
      return _builder_1.toString();
    }
  }
  
  public static String computeExpression(final EObject exp) {
    if (exp instanceof Div) {
      return _computeExpression((Div)exp);
    } else if (exp instanceof ExternalP) {
      return _computeExpression((ExternalP)exp);
    } else if (exp instanceof LetBinding) {
      return _computeExpression((LetBinding)exp);
    } else if (exp instanceof MathNumber) {
      return _computeExpression((MathNumber)exp);
    } else if (exp instanceof Minus) {
      return _computeExpression((Minus)exp);
    } else if (exp instanceof Mult) {
      return _computeExpression((Mult)exp);
    } else if (exp instanceof Par) {
      return _computeExpression((Par)exp);
    } else if (exp instanceof Plus) {
      return _computeExpression((Plus)exp);
    } else if (exp instanceof VarBinding) {
      return _computeExpression((VarBinding)exp);
    } else if (exp instanceof VariableUse) {
      return _computeExpression((VariableUse)exp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp).toString());
    }
  }
  
  public static String computeBinding(final Binding binding) {
    if (binding instanceof LetBinding) {
      return _computeBinding((LetBinding)binding);
    } else if (binding instanceof VarBinding) {
      return _computeBinding((VarBinding)binding);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(binding).toString());
    }
  }
}
