/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide;

import com.google.inject.Injector;
import dk.sdu.mmmi.mdsd.MathStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MathIdeSetup extends MathStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from MathIdeModule to Module");
  }
}
